# Import Blueprint to modularize routes
# render_template is used to render HTML pages
from flask import Blueprint, render_template, session


# login_required ensures only logged-in users can access this route
# current_user gives details of the logged-in user
from flask_login import login_required, current_user

# Import Income and Expense models to fetch data from database
from models.income import Income
from models.expense import Expense


# Create a Blueprint for view-related routes
view_data_blueprint = Blueprint('view_data', __name__)


# Route to view income and expense data
# This route loads the dashboard page with "View Data" tab active
@view_data_blueprint.route('/view', methods=['GET'])
@login_required
def view_data():
    # Debug: Print current user object
    print("Current User:", current_user)

    # Debug: Print logged-in user's ID
    print("Current User ID:", current_user.id)

    # Fetch all incomes belonging to the logged-in user
    incomes = Income.query.filter_by(user_id=current_user.id).all()

    # Fetch all expenses belonging to the logged-in user
    expenses = Expense.query.filter_by(user_id=current_user.id).all()
    total_income = sum(income.amount for income in incomes)
    total_expense = sum(expense.amount for expense in expenses)
    balance = total_income - total_expense


    # Debug: Print fetched incomes and expenses
    print("Fetched Incomes:", incomes)
    print("Fetched Expenses:", expenses)

    # Placeholder for AI-generated advice
    # This will later store messages generated by the AI agent
    # For now, it is set to None so the dashboard loads safely
    ai_advice = session.pop('ai_advice', None)


    # Render the dashboard page and pass required data
    # active_tab='view' keeps the "View Data" tab open
    # ai_advice is passed so AI Insight box can appear when available
    return render_template(
    'dashboard.html',
    incomes=incomes,
    expenses=expenses,
    active_tab='view',
    total_income=total_income,
    total_expense=total_expense,
    balance=balance
)

    